# Workflow para generar el Readme
---
name: Generate README.md based on json files

on:
  push:
    branches: [main]

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - name: install deps
        run: cd .github/actions && npm ci --omit=dev
      - name: Generate Readme
        run: cd .github/actions && npm run generate
      - name: Generate missing
        run: cd .github/actions && npm run generate-missing
      - name: Add and commit changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "[bot] Generate README.md based on .json files"
          file_pattern: README.md
