# Workflow para generar el badge de que sitios siguen vivos
---
name: Sitios vivos check

on:
  push:
    branches: [main]
  schedule:
    # every 4 hours
    - cron: "0 0/4 * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: install deps
        run: (cd .github/actions && npm i --only=prod)
      - name: check sites
        run: (cd .github/actions && npm run site-check)
      - name: Deploy to reachable-sites branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./_badges
          publish_branch: reachable-sites
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
